/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProductManager;
import Model.Product;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author huutr
 */
public class AddMatHang extends javax.swing.JFrame {

    /**
     * Creates new form MatHang
     */
    public AddMatHang() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                      
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jl_TypeMH = new javax.swing.JLabel();
        tf_TypeMH = new javax.swing.JTextField();
        jl_IDMH = new javax.swing.JLabel();
        tf_IDMH = new javax.swing.JTextField();
        jl_NameMH = new javax.swing.JLabel();
        tfl_NameMH = new javax.swing.JTextField();
        jl_ProducerMH = new javax.swing.JLabel();
        tf_ProducerMH = new javax.swing.JTextField();
        jl_InformationMH = new javax.swing.JLabel();
        jl_AmountMH = new javax.swing.JLabel();
        tf_AmountMH = new javax.swing.JTextField();
        jl_PriceMH = new javax.swing.JLabel();
        tfl_PriceMH = new javax.swing.JTextField();
        jl_VND = new javax.swing.JLabel();
        btn_AddMH = new javax.swing.JButton();
        btn_BackMH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        jl_TypeMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_TypeMH.setText("Phân loại");

        jl_IDMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_IDMH.setText("Mã Mặt hàng:");

        jl_NameMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_NameMH.setText("Tên Mặt hàng:");

        jl_ProducerMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_ProducerMH.setText("Hãng Sản xuất:");

        jl_InformationMH.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jl_InformationMH.setText("THÔNG TIN MẶT HÀNG");

        jl_AmountMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_AmountMH.setText("Số lượng:");

        jl_PriceMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_PriceMH.setText("Đơn giá:");

        jl_VND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_VND.setText("VND");

        btn_AddMH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_AddMH.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\Code java\\QLBH\\display\\buttons\\thêm 23.png")); // NOI18N
        btn_AddMH.setText("Thêm");
        btn_AddMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddMHActionPerformed(evt);
            }
        });

        btn_BackMH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_BackMH.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\Code java\\QLBH\\display\\buttons\\thoát 23.png")); // NOI18N
        btn_BackMH.setText("Quay lại");
        btn_BackMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jl_NameMH)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfl_NameMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jl_IDMH)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_IDMH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_ProducerMH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_AddMH, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_ProducerMH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_AmountMH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_AmountMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_TypeMH)
                                .addGap(18, 18, 18)
                                .addComponent(tf_TypeMH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_BackMH, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jl_PriceMH)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfl_PriceMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_VND)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_InformationMH)
                .addGap(178, 178, 178))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tf_AmountMH, tf_TypeMH, tfl_NameMH, tfl_PriceMH});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jl_InformationMH)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_TypeMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_TypeMH)
                    .addComponent(tf_IDMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_IDMH))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NameMH)
                    .addComponent(tfl_NameMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_AmountMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_AmountMH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfl_PriceMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_PriceMH)
                    .addComponent(tf_ProducerMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_ProducerMH)
                    .addComponent(jl_VND))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_BackMH)
                    .addComponent(btn_AddMH))
                .addGap(37, 37, 37))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\Code java\\QLBH\\display\\backgrounds\\wp600x400.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>             

    private void btn_BackMHActionPerformed(java.awt.event.ActionEvent evt) {                                           
        this.setVisible(false);
    }                                          

    private void btn_AddMHActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int flag = 0;
        try
        {
            String MaMH = tf_IDMH.getText();
            String TenMH = tfl_NameMH.getText();
            String HangSx = tf_ProducerMH.getText();
            String LoaiMH = tf_TypeMH.getText();
            flag = 1;
            int SoLuong = Integer.parseInt(tf_AmountMH.getText());
            flag = 2;
            int DonGia = Integer.parseInt(tfl_PriceMH.getText());
            if (TenMH.equals("") || HangSx.equals("") || String.valueOf(SoLuong).equals("") || String.valueOf(DonGia).equals("")||MaMH.equals("")||LoaiMH.equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!");
            }
            else {
                try {
                    ProductManager pm = new ProductManager();
                    pm.addProduct(MaMH, TenMH, HangSx,LoaiMH, SoLuong, DonGia);
                    JOptionPane.showMessageDialog(null, "Thêm thành công!");   
                    tf_IDMH.setText("");
                    tfl_NameMH.setText("");
                    tf_ProducerMH.setText("");
                    tf_TypeMH.setText("");
                    tf_AmountMH.setText("");     
                    tfl_PriceMH.setText("");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddMatHang.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(AddMatHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (NumberFormatException ex){
            switch(flag)
            {
                case 1:
                {
                    JOptionPane.showMessageDialog(null, "Rất tiếc, bạn đã nhập sai định dạng cho số lượng!\nVui lòng nhập lại!");
                    tf_AmountMH.setText("");
                    break;
                }
                 case 2:
                {
                    JOptionPane.showMessageDialog(null, "Rất tiếc, bạn đã nhập sai định dạng cho đơn giá!\nVui lòng nhập lại!");
                    tfl_PriceMH.setText("");
                    break;
                }
            }
        } 
    }                                         

                 
    private javax.swing.JButton btn_AddMH;
    private javax.swing.JButton btn_BackMH;
    private javax.swing.JLabel jl_VND;
    private javax.swing.JLabel jl_AmountMH;
    private javax.swing.JLabel jl_IDMH;
    private javax.swing.JLabel jl_InformationMH;
    private javax.swing.JLabel jl_NameMH;
    private javax.swing.JLabel jl_PriceMH;
    private javax.swing.JLabel jl_ProducerMH;
    private javax.swing.JLabel jl_TypeMH;
    private javax.swing.JTextField tf_AmountMH;
    private javax.swing.JTextField tf_IDMH;
    private javax.swing.JTextField tf_ProducerMH;
    private javax.swing.JTextField tf_TypeMH;
    private javax.swing.JTextField tfl_NameMH;
    private javax.swing.JTextField tfl_PriceMH;    
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel1;
}


