/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProductManager;
import Model.Product;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author huutr
 */
public class AddMatHang extends javax.swing.JFrame {

    /**
     * Creates new form MatHang
     */
    public AddMatHang() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                      
    private void initComponents() {

        jl_InformationMH = new javax.swing.JLabel();
        jl_NameMH = new javax.swing.JLabel();
        jl_ProducerMH = new javax.swing.JLabel();
        tfl_NameMH = new javax.swing.JTextField();
        tf_ProducerMH = new javax.swing.JTextField();
        btn_AddMH = new javax.swing.JButton();
        btn_BackMH = new javax.swing.JButton();
        tf_AmountMH = new javax.swing.JTextField();
        tfl_PriceMH = new javax.swing.JTextField();
        jl_AmountMH = new javax.swing.JLabel();
        jl_PriceMH = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jl_TypeMH = new javax.swing.JLabel();
        tf_TypeMH = new javax.swing.JTextField();
        jl_IDMH = new javax.swing.JLabel();
        tf_IDMH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_InformationMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_InformationMH.setText("THÔNG TIN MẶT HÀNG");

        jl_NameMH.setText("Tên mặt hàng:");

        jl_ProducerMH.setText("Hãng sản xuất:");

        btn_AddMH.setText("Thêm");
        btn_AddMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddMHActionPerformed(evt);
            }
        });

        btn_BackMH.setText("Quay lại");
        btn_BackMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackMHActionPerformed(evt);
            }
        });

        jl_AmountMH.setText("Số lượng:");

        jl_PriceMH.setText("Đơn giá:");

        jLabel7.setText("đ");

        jl_TypeMH.setText("Loại mặt hàng:");


        jl_IDMH.setText("Mã mặt hàng");
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_AddMH, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btn_BackMH, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_ProducerMH)
                                    .addComponent(jl_TypeMH)
                                    .addComponent(jl_NameMH)
                                    .addComponent(jl_AmountMH)
                                    .addComponent(jl_PriceMH)
                                    .addComponent(jl_IDMH))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfl_NameMH)
                                    .addComponent(tf_ProducerMH)
                                    .addComponent(tf_TypeMH)
                                    .addComponent(tf_AmountMH)
                                    .addComponent(tfl_PriceMH)
                                    .addComponent(tf_IDMH, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jl_InformationMH, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jl_InformationMH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_IDMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_IDMH))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfl_NameMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_NameMH))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ProducerMH)
                    .addComponent(tf_ProducerMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_TypeMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_TypeMH))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_AmountMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_AmountMH))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfl_PriceMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jl_PriceMH))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AddMH)
                    .addComponent(btn_BackMH))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>                        

    private void btn_BackMHActionPerformed(java.awt.event.ActionEvent evt) {                                           
        this.setVisible(false);
    }                                          

    private void btn_AddMHActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String MaMH = tf_IDMH.getText();
        String TenMH = tfl_NameMH.getText();
        String HangSx = tf_ProducerMH.getText();
        String LoaiMH = tf_TypeMH.getText();
        String SoLuong = tf_AmountMH.getText();
        String DonGia = tfl_PriceMH.getText();
        if (TenMH.equals("") || HangSx.equals("") || SoLuong.equals("") || DonGia.equals("")||MaMH.equals("")||LoaiMH.equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!");
        }
        else {
            try {
                ProductManager pm = new ProductManager();
                pm.addProduct(MaMH, TenMH, HangSx,LoaiMH, Integer.parseInt(SoLuong), Integer.parseInt(DonGia));
                JOptionPane.showMessageDialog(null, "Thêm thành công!");   
               tf_IDMH.setText("");
                tfl_NameMH.setText("");
                 tf_ProducerMH.setText("");
               tf_TypeMH.setText("");
                tf_AmountMH.setText("");     
                tfl_PriceMH.setText("");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddMatHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(AddMatHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }                                         

                 
    private javax.swing.JButton btn_AddMH;
    private javax.swing.JButton btn_BackMH;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jl_AmountMH;
    private javax.swing.JLabel jl_IDMH;
    private javax.swing.JLabel jl_InformationMH;
    private javax.swing.JLabel jl_NameMH;
    private javax.swing.JLabel jl_PriceMH;
    private javax.swing.JLabel jl_ProducerMH;
    private javax.swing.JLabel jl_TypeMH;
    private javax.swing.JTextField tf_AmountMH;
    private javax.swing.JTextField tf_IDMH;
    private javax.swing.JTextField tf_ProducerMH;
    private javax.swing.JTextField tf_TypeMH;
    private javax.swing.JTextField tfl_NameMH;
    private javax.swing.JTextField tfl_PriceMH;                
}


