package View;

import Controller.BillManager;
import Controller.StaffManager;
import Model.Cart;
import Model.Staff;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class HoaDon extends javax.swing.JFrame {


    public HoaDon() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);   
        int TongGH = 0;
        try {           
            BillManager bm = new BillManager();  
            StaffManager sm = new StaffManager();
            this.listGH = bm.getListGH_follow_TenMH();
            Model model = new Model();
            this.tb_Bill.setModel(model);
            for(Cart gh: listGH)
            {
                TongGH = TongGH + gh.getThanhTien();
            }
            jl_TotalBill.setText(String.valueOf(TongGH)+" VNĐ");
            
            //chuyển số tiền thành chữ
            jl_TotalBill_Text.setText(bm.numberToString(new BigDecimal(String.valueOf(TongGH)))+" chẵn");        
            
               //Đưa tên nhân viên lập hóa đơn lên hóa đơn
            int MaNVHT = sm.getMaNVHT_follow_Status(1);   //Lấy Mã nhân viên đăng nhập
            if(MaNVHT != 0)
            {
                Staff nv = sm.getDetail(MaNVHT);              //Lấy nhân viên đăng nhập theo mã nhân viên vừa lấy được
                String NameNVHT = nv.getName();               //Lấy tên nhân viên
                jl_NameNV_Lap_HD.setText(NameNVHT);           //Đưa tên nhân viên lên hóa đơn
            }
            else jl_NameNV_Lap_HD.setText("ADMIN"); 
            
            //Lấy KH có trạng thái là 1 (KH mới được thêm từ bên giỏ hàng thì sẽ có trạng thái là 1)
            this.listKH = sm.getListKH(1);  

              //Đưa dữ liệu KH lên hóa đơn
            jl_NameKH.setText(listKH.get(0).getName());
            jl_Address.setText(listKH.get(0).getAddress());
            jl_PhoneKH.setText(Integer.toString(listKH.get(0).getPhone()));
            
            //Đưa KH trở thành KH cũ 
            sm.setKH_Status(0, listKH.get(0).getPhone());
                   
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GioHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(GioHang.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    List<Staff> listKH = new ArrayList<>();
    List<Cart> listGH = new ArrayList<>();
    
    private class Model extends DefaultTableModel{

        @Override
        public Object getValueAt(int row, int column) {
            switch (column){
                case 0:
                    return listGH.get(row).getStt();
                case 1:
                    return listGH.get(row).getTenMHGH();
                case 2:
                    return listGH.get(row).getDonGiaGH();
                case 3:
                    return listGH.get(row).getSoLuongMua();
                case 4:
                    return listGH.get(row).getThanhTien();
            }
            return null;
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }

        @Override
        public String getColumnName(int column) {
            switch (column){
                case 0:
                    return "STT";
                case 1:
                    return "Tên mặt hàng";
                case 2: 
                    return "Đơn giá";
                case 3:
                    return "Số lượng mua";
                case 4:
                    return "Thành tiền";
            }
            return null; 
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public int getRowCount() {
            return listGH.size();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        SieuThiDienMay = new javax.swing.JLabel();
        LyTuong = new javax.swing.JLabel();
        HoaDon = new javax.swing.JLabel();
        Chuyen = new javax.swing.JLabel();
        ThietBi = new javax.swing.JLabel();
        DoGiaDung = new javax.swing.JLabel();
        SanPhamCongNghe = new javax.swing.JLabel();
        DC_SieuThi1 = new javax.swing.JLabel();
        DC_SieuThi2 = new javax.swing.JLabel();
        SDT_SieuThi = new javax.swing.JLabel();
        NguoiMuaHang = new javax.swing.JLabel();
        SDT = new javax.swing.JLabel();
        DC = new javax.swing.JLabel();
        jl_NameKH = new javax.swing.JLabel();
        jl_PhoneKH = new javax.swing.JLabel();
        jl_Address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Bill = new javax.swing.JTable();
        jl_ChuKy1 = new javax.swing.JLabel();
        jl_KH = new javax.swing.JLabel();
        jl_NV = new javax.swing.JLabel();
        jl_ChuKy2 = new javax.swing.JLabel();
        jl_TongTien = new javax.swing.JLabel();
        jl_TienChu = new javax.swing.JLabel();
        jl_TotalBill = new javax.swing.JLabel();
        jl_TotalBill_Text = new javax.swing.JLabel();
        HangChinhHang = new javax.swing.JLabel();
        NhanVienLapHD = new javax.swing.JLabel();
        jl_NameNV_Lap_HD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SieuThiDienMay.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        SieuThiDienMay.setForeground(new java.awt.Color(255, 0, 0));
        SieuThiDienMay.setText("SIÊU THỊ ĐIỆN MÁY");

        LyTuong.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        LyTuong.setForeground(new java.awt.Color(255, 0, 0));
        LyTuong.setText("LÝ TƯỞNG");

        HoaDon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HoaDon.setForeground(new java.awt.Color(255, 0, 0));
        HoaDon.setText("HÓA ĐƠN BÁN HÀNG");

        Chuyen.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Chuyen.setForeground(new java.awt.Color(255, 0, 0));
        Chuyen.setText("Chuyên cung cấp, phân phối");

        ThietBi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ThietBi.setForeground(new java.awt.Color(255, 0, 0));
        ThietBi.setText("-Thiết bị điện tử, điện lạnh");

        DoGiaDung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DoGiaDung.setForeground(new java.awt.Color(255, 0, 0));
        DoGiaDung.setText("-Đồ gia dụng, vệ sinh");

        SanPhamCongNghe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SanPhamCongNghe.setForeground(new java.awt.Color(255, 0, 0));
        SanPhamCongNghe.setText("-Sản phẩm công nghệ");

        DC_SieuThi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DC_SieuThi1.setForeground(new java.awt.Color(255, 0, 0));
        DC_SieuThi1.setText("Đc: Ngã 3 chợ Bương,");

        DC_SieuThi2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DC_SieuThi2.setForeground(new java.awt.Color(255, 0, 0));
        DC_SieuThi2.setText("Cấn Hữu, Quốc Oai, Hà Nội");

        SDT_SieuThi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SDT_SieuThi.setForeground(new java.awt.Color(255, 0, 0));
        SDT_SieuThi.setText("ĐT: 0933181678 - 0936217519 ");

        NguoiMuaHang.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        NguoiMuaHang.setForeground(new java.awt.Color(255, 0, 0));
        NguoiMuaHang.setText("Người mua hàng: ");

        SDT.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        SDT.setForeground(new java.awt.Color(255, 0, 0));
        SDT.setText("Số điện thoại: ");

        DC.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        DC.setForeground(new java.awt.Color(255, 0, 0));
        DC.setText("Địa chỉ: ");

        jl_NameKH.setBackground(new java.awt.Color(0, 0, 0));
        jl_NameKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jl_NameKH.setText("Tên người mua hàng");

        jl_PhoneKH.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jl_PhoneKH.setText("Số điện thoại");

        jl_Address.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jl_Address.setText("Địa chỉ");

        tb_Bill.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        tb_Bill.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tb_Bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mặt hàng", "Đơn giá", "Số luọng", "Thành tiền"
            }
        ));
        tb_Bill.setGridColor(new java.awt.Color(255, 0, 0));
        tb_Bill.setRowHeight(20);
        tb_Bill.setRowMargin(10);
        tb_Bill.setSelectionBackground(new java.awt.Color(0, 102, 204));
        jScrollPane1.setViewportView(tb_Bill);

        jl_ChuKy1.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        jl_ChuKy1.setForeground(new java.awt.Color(255, 0, 0));
        jl_ChuKy1.setText("(Ký rõ họ tên)");

        jl_KH.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jl_KH.setForeground(new java.awt.Color(255, 0, 0));
        jl_KH.setText("NGƯỜI MUA HÀNG");

        jl_NV.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jl_NV.setForeground(new java.awt.Color(255, 0, 0));
        jl_NV.setText("NGƯỜI TẠO HÓA ĐƠN");

        jl_ChuKy2.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        jl_ChuKy2.setForeground(new java.awt.Color(255, 0, 0));
        jl_ChuKy2.setText("(Ký rõ họ tên)");

        jl_TongTien.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jl_TongTien.setForeground(new java.awt.Color(255, 0, 0));
        jl_TongTien.setText("Tổng tiền thanh toán:");

        jl_TienChu.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jl_TienChu.setForeground(new java.awt.Color(255, 0, 0));
        jl_TienChu.setText("Bằng chữ:");

        jl_TotalBill.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jl_TotalBill.setText("Tổng tiền");

        jl_TotalBill_Text.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jl_TotalBill_Text.setText("Tiền");

        HangChinhHang.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        HangChinhHang.setForeground(new java.awt.Color(255, 0, 0));
        HangChinhHang.setText("hàng chính hãng");

        NhanVienLapHD.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        NhanVienLapHD.setForeground(new java.awt.Color(255, 0, 0));
        NhanVienLapHD.setText("Nhân viên lập HĐ:");

        jl_NameNV_Lap_HD.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jl_NameNV_Lap_HD.setText("Tên nhân viên lập hóa đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(DC_SieuThi2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SDT_SieuThi)
                        .addGap(88, 88, 88)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoGiaDung, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThietBi)
                    .addComponent(SanPhamCongNghe, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jl_TienChu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_TotalBill_Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jl_TongTien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_TotalBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(196, 196, 196))))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SieuThiDienMay, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 370, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(DC_SieuThi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HangChinhHang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(LyTuong, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(HoaDon)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Chuyen)
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jl_ChuKy1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_ChuKy2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jl_KH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_NV)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_PhoneKH, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NguoiMuaHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl_NameKH, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NhanVienLapHD)
                        .addGap(18, 18, 18)
                        .addComponent(jl_NameNV_Lap_HD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SieuThiDienMay)
                    .addComponent(HoaDon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LyTuong)
                    .addComponent(Chuyen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DC_SieuThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HangChinhHang))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DC_SieuThi2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoGiaDung)
                    .addComponent(SDT_SieuThi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SanPhamCongNghe)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NhanVienLapHD)
                    .addComponent(jl_NameNV_Lap_HD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NguoiMuaHang)
                    .addComponent(jl_NameKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDT)
                    .addComponent(jl_PhoneKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DC)
                    .addComponent(jl_Address))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_TongTien)
                    .addComponent(jl_TotalBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_TienChu)
                    .addComponent(jl_TotalBill_Text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_KH)
                    .addComponent(jl_NV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ChuKy1)
                    .addComponent(jl_ChuKy2))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify                     
    private javax.swing.JLabel Chuyen;
    private javax.swing.JLabel DC;
    private javax.swing.JLabel DC_SieuThi1;
    private javax.swing.JLabel DC_SieuThi2;
    private javax.swing.JLabel DoGiaDung;
    private javax.swing.JLabel HangChinhHang;
    private javax.swing.JLabel HoaDon;
    private javax.swing.JLabel LyTuong;
    private javax.swing.JLabel NguoiMuaHang;
    private javax.swing.JLabel NhanVienLapHD;
    private javax.swing.JLabel SDT;
    private javax.swing.JLabel SDT_SieuThi;
    private javax.swing.JLabel SanPhamCongNghe;
    private javax.swing.JLabel SieuThiDienMay;
    private javax.swing.JLabel ThietBi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_Address;
    private javax.swing.JLabel jl_ChuKy1;
    private javax.swing.JLabel jl_ChuKy2;
    private javax.swing.JLabel jl_KH;
    private javax.swing.JLabel jl_NV;
    private javax.swing.JLabel jl_NameKH;
    private javax.swing.JLabel jl_NameNV_Lap_HD;
    private javax.swing.JLabel jl_PhoneKH;
    private javax.swing.JLabel jl_TienChu;
    private javax.swing.JLabel jl_TongTien;
    private javax.swing.JLabel jl_TotalBill;
    private javax.swing.JLabel jl_TotalBill_Text;
    private javax.swing.JTable tb_Bill;
    // End of variables declaration                   
}
