/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Son
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Welcome = new javax.swing.JLabel();
        jl_Login = new javax.swing.JLabel();
        jl_Account = new javax.swing.JLabel();
        jl_Password = new javax.swing.JLabel();
        tf_Account = new javax.swing.JTextField();
        tf_PassWord = new javax.swing.JTextField();
        jbn_BackLG = new javax.swing.JButton();
        btn_Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jl_Welcome.setBackground(java.awt.Color.white);
        jl_Welcome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Welcome.setText("Chào mừng bạn đến với QUẢN LÝ BÁN HÀNG!");

        jl_Login.setBackground(java.awt.Color.white);
        jl_Login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_Login.setIcon(new javax.swing.ImageIcon("C:\\Users\\Son\\Desktop\\QLBH-main\\QLBH-main\\images\\buttons\\icons8-male-user-48.png")); // NOI18N
        jl_Login.setText("ĐĂNG NHẬP");

        jl_Account.setBackground(java.awt.Color.white);
        jl_Account.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_Account.setText("Tên đăng nhập:");

        jl_Password.setBackground(java.awt.Color.white);
        jl_Password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_Password.setText("Mật khẩu:");

        tf_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_AccountActionPerformed(evt);
            }
        });

        tf_PassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_PassWordActionPerformed(evt);
            }
        });

        jbn_BackLG.setBackground(new java.awt.Color(60, 115, 195));
        jbn_BackLG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbn_BackLG.setForeground(java.awt.Color.white);
        jbn_BackLG.setText("Thoát");
        jbn_BackLG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_BackLGActionPerformed(evt);
            }
        });

        btn_Login.setBackground(new java.awt.Color(60, 115, 195));
        btn_Login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Login.setForeground(java.awt.Color.white);
        btn_Login.setText("Đăng nhập");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jbn_BackLG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Login)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jl_Login))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_Welcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Account)
                            .addComponent(jl_Password))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_PassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_Welcome)
                .addGap(32, 32, 32)
                .addComponent(jl_Login)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Account)
                    .addComponent(tf_Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Password)
                    .addComponent(tf_PassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbn_BackLG)
                    .addComponent(btn_Login))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void jbn_BackLGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_BackLGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_BackLGActionPerformed

    private void tf_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_AccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_AccountActionPerformed

    private void tf_PassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_PassWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_PassWordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton jbn_BackLG;
    private javax.swing.JLabel jl_Account;
    private javax.swing.JLabel jl_Login;
    private javax.swing.JLabel jl_Password;
    private javax.swing.JLabel jl_Welcome;
    private javax.swing.JTextField tf_Account;
    private javax.swing.JTextField tf_PassWord;
    // End of variables declaration//GEN-END:variables
}
